set(APP_SRC
    "src/setup.cpp"
    "src/common/logHandeler.cpp"
    "src/common/global.cpp"
    "src/common/fileHandeler.cpp"
    "src/common/localesHandeler.cpp"
    "src/common/sessionManager.cpp"
    "src/_UI/WindowManager.cpp"
    "src/_UI/themeManager.cpp"
    "src/plugins/PluginLoader.cpp"
    "src/plugins/PluginManager.cpp"
)